### ISSUE TITLE
Use markdown instead of HTML for code of conduct

### ISSUE THREAD

**Issue by salcode** [burbswp/code-of-conduct#2]
I think we should consider using markdown instead of HTML for the code of conduct.

I think the big benefit is markdown is easier to read when in source code form.

Additionally, GitHub will automatically render it as HTML when viewed through GitHub and it is relatively easy to convert it to HTML (e.g. online [markdown to HTML conversion](https://www.browserling.com/tools/markdown-to-html) tool)

Since the HTML is pretty straight forward, we would change

## `H1`

To

```
# Code of Conduct
```

### From

```
<h2>Purpose<h2>
```

to

```
## Purpose
```

### From

```
<ul>
<li>Be considerate, respectful, and collaborative.</li>
<li>Refrain from demeaning, discriminatory or harassing behavior and speech.</li>
<li>Be mindful of your surroundings and of your fellow participants. Alert conference organizers if you notice a dangerous situation or someone in distress.</li>
<li>Participate in an authentic and active way. In doing so, you help to create WordCamp Philadelphia and make it your own.</li>
</ul>
```

### To

```
- Be considerate, respectful, and collaborative.
- Refrain from demeaning, discriminatory or harassing behavior and speech.
- Be mindful of your surroundings and of your fellow participants. Alert conference organizers if you notice a dangerous situation or someone in distress.
- Participate in an authentic and active way. In doing so, you help to create WordCamp Philadelphia and make it your own.
```

**Comment by liamdempsey** [comment]
I think I made the correct edits to the Code of Conduct to make it display in markdown, but I'm sure that I did. When you get a moment, would you mind please double-checking my work? Thanks!

**Comment by salcode** [comment]
The markdown itself looks good. 👍 

I'd recommend changing the filename from `code-of-conduct` to `code-of-conduct.md`, which would cause GitHub to render the markdown as HTML when previewing.

**Comment by liamdempsey** [comment]
Perfect! Thanks!

**Comment by salcode** [comment]
Looks great 👍
